### ISSUE TITLE
cknow/laravel-money v0.1.7 requires ext-intl * -> the requested PHP extension intl is missing from your system.

### ISSUE THREAD

**Issue by canfiax** [cknow/laravel-money#1]
Awesome package, however, I am getting the following error when trying to install.

    cknow/laravel-money v0.1.7 requires ext-intl * -> the requested PHP extension intl is missing from your system.

I have tried requiring the `"symfony/intl": "~2.7"` but that does not work.

**Comment by canfiax** [comment]
Thanks to @fsec from #laravel IRC, the following will work:


    sudo apt-get update && sudo apt-get install php5-intl
    service php5-fpm restart

**Comment by ricardogobbosouza** [comment]
Thank you for using my package, i will soon describe how to use.
Sorry my bad english! :(
