### ISSUE TITLE
Breaking change in 6.2.0

### ISSUE THREAD

**Issue by jbardnz** [cknow/laravel-money#103]
Hey team,

Firstly thanks for all the work you do on this package. 

I noticed the recent release contains a fairly major breaking change that isn't obvious. Previously the `money()` function would accept null values however this now throws an error:

![image](https://user-images.githubusercontent.com/1628446/149683588-7157e195-2433-462a-94c6-fc9d0814bbd0.png)

This issue caused a few issues on production, I wonder if this would be more suitable being a 7.0 release rather than a point release?

**Comment by ricardogobbosouza** [comment]
Hy @jbardnz 

I'll add support for null values, so it doesn't generate a breaking change

Thanks for reporting

**Comment by phadaphunk** [comment]
This issue is still present in `6.3.0`
