### ISSUE TITLE
error Class

### ISSUE THREAD

**Issue by intrepidtr** [cknow/laravel-money#11]
Add App;
ClickNow\Money\MoneyServiceProvider::class,

Add My Class;
use ClickNow\Money\Money;

Example:
return  Money::BRL(500); 

Error:
Class 'ClickNow\Money\Money' not found

**Comment by miloandco** [comment]
confirmed, same issue.

**Comment by ricardogobbosouza** [comment]
Please show me your `composer.json` or try run `composer dump-autoload`

composer.json
```
{
  "name": "teste",
  "require": {
    "cknow/laravel-money": "~1.0.3"
  }
}
```

index.php
```
<?php

require 'vendor/autoload.php';

use ClickNow\Money\Money;

echo Money::BRL(500);
```
