### ISSUE TITLE
Currencies list with description & symbol

### ISSUE THREAD

**Issue by achatzi78** [cknow/laravel-money#110]
Hello and thank you for a very useful project.

I was wondering if there is a way to have a currencies list with code, description and symbol in order to display to the user.

I would like to create a select input in order for the user to select the desired currency from the available ones, so a list like

```php
[
    'EUR' => 'Euro',
    'USD' => 'US Dollars',
]
```

would be very helpful.

Also, a way to display the symbol of a currency would be helpful too.  For example, if I have an invoice that all prices are in the same currency, I prefer to display the currency symbol in the header of the table, like this _Price ($)_. So if I could do something like `currency('USD')->symbol` would be great.

Is there a way to do these things that I missed or is it something that has to be implemented?

Thanks again for a great project.

**Comment by ricardogobbosouza** [comment]
Hi @achatzi78

To access currency descriptions https://github.com/moneyphp/money/blob/master/resources/currency.php it is necessary to create PR for this, today we do not have access https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php

For the currency symbol I recommend using https://www.php.net/manual/pt_BR/class.numberformatter.php
