### ISSUE TITLE
Weird rounding behaviour?

### ISSUE THREAD

**Issue by timvonwerne** [cknow/laravel-money#115]
Hi,
I noticed today, that my functions which worked flawlessly before, suddenly show up totally false values. The issue seems to happen every time that I use the multiply operation:

```php
return \Cknow\Money\Money::EUR(2500)->multiply(2.5); // returns 50,00 € instead of (obviously) 62,5 €
return \Cknow\Money\Money::EUR(2500)->multiply(13.75); // returns 325,00 € instead of 343,75 €
return \Cknow\Money\Money::EUR(2500)->multiply(12); // returns 300,00 € like it should
```

As you can see from the examples above, the issue only occurs when multiplying with decimal numbers.
Were there any breaking changes I haven't noticed yet? Can anyone help me out with an explanation please? Cheers!

**Comment by ricardogobbosouza** [comment]
Hi @timvonwerne 
I will check but nothing has changed to have this break change

**Comment by ricardogobbosouza** [comment]
MoneyPHP always round the value

v4 https://github.com/moneyphp/money/blob/v4.0.3/src/Money.php#L247
v3 https://github.com/moneyphp/money/blob/v3.3.1/src/Money.php#L317

I will work on a fix

**Comment by timvonwerne** [comment]
Hi @ricardogobbosouza,
first of all: thanks for the quick fix!

Just one question: I updated the package and the rounding error persists. Is there anything I need to change regarding rounding mode (e.g. turn rounding off, give a second parameter to the rounding function, etc.)? Caches are already cleared.
