### ISSUE TITLE
Problem with cents in v6.5.1

### ISSUE THREAD

**Issue by quintavallechristian** [cknow/laravel-money#123]
Updating to the last version (coming from 3.8) I noticed all the amounts in my application multiplied by 100.  It seems like the format() function does not divide by 100 anymore, so if I pass a value of 100 it will print 100 € (or whatever currency I set).

Rolling back to version 6.4.0 the problem disappears

**Comment by ReadingPride** [comment]
We had the same problem which caught us out by surprise.

**Comment by marvinschroeder** [comment]
Same problem here.

**Comment by hrnicek** [comment]
Same problem

**Comment by ricardogobbosouza** [comment]
Hi @quintavallechristian 
Could you share an example of the error?

**Comment by marvinschroeder** [comment]
This problem only occurs with float's.

In v6.4.0 this was the behavior:
```
money(250, 'EUR') // 2,50 €
money(2.50 * 100, 'EUR') // 2,50 €
```

In v6.5.1:
```
money(250, 'EUR') // 2,50 €
money(2.50 * 100, 'EUR') // 250,00 €
```

**Comment by ricardogobbosouza** [comment]
Actually this is expected now

Because 250 is not equal to (2.50 * 100) = 250.0

We have different treatments for integers and floating
https://github.com/cknow/laravel-money/blob/main/src/MoneyParserTrait.php#L32-L74

And so a `forceDecimals` option has been added
https://github.com/cknow/laravel-money/blob/main/src/Money.php#L73-L76

Maybe this should have been a break change and released v7 🤔

**Comment by marvinschroeder** [comment]
If that is expected now, it is indeed a breaking change and better suited for a new major version.

**Comment by ricardogobbosouza** [comment]
I treated this as a fix

In v6.4.0

```php
@money(2.50 * 101) = $2.52 // wrong
```

In v6.5.1:

```php
@money(2.50 * 101) = $252.50 // right
```

**Comment by ricardogobbosouza** [comment]
Sorry for the trouble with the floating values
Released [v7.0.0](https://github.com/cknow/laravel-money/releases/tag/v7.0.0)

**Comment by jtomek** [comment]
This was indeed a breaking change. Our app reports significant numeric changes to our clients and suddenly we generated quite a number of notifications because all figures suddenly went up by x100. :) We need to add more testing.

**Comment by giacomok** [comment]
> I treated this as a fix
> 
> In v6.4.0
> 
> ```
> @money(2.50 * 101) = $2.52 // wrong
> ```

why this should be wrong?
