### ISSUE TITLE
Loss of precision when multiplying or dividing by a float/string

### ISSUE THREAD

**Issue by marwins** [cknow/laravel-money#126]
> Version : v7.0.0

Hello,

when we multiply or divide a  Cknow\Money\Money by a float or float cast to string, we loose some precision, the result seems to be truncated.

## Actual behavior
```php
use Cknow\Money\Money;

$recRatio = 0.16666666666667;
$annualPitTotal =  Money::parseByDecimal((string)199.00, Money::getDefaultCurrency());
$periodPitTotal = $annualPitTotal->multiply((string)$recRatio);

echo $periodPitTotal->getAmount(); // "3316"
```

## Expected behavior
```php
use Cknow\Money\Money;

$recRatio = 0.16666666666667;
$annualPitTotal =  Money::parseByDecimal((string)199.00, Money::getDefaultCurrency());
$periodPitTotal = $annualPitTotal->multiply((string)$recRatio);

echo $periodPitTotal->getAmount(); // "3317"
```

This is link to the fact that calculator result is directly cast to Int without being rounded :

- https://github.com/cknow/laravel-money/blob/2bacfb2008dc96ef9d733312baf56df1a833e609/src/Money.php#L128
- https://github.com/cknow/laravel-money/blob/2bacfb2008dc96ef9d733312baf56df1a833e609/src/Money.php#L106

`return new self((int) round($calculator->divide($money->getAmount(), $divisor), 0, $roundingMode), $money->getCurrency());` 
`return new self((int) round($calculator->multiply($money->getAmount(), $multiplier), 0, $roundingMode), $money->getCurrency());`

would be more accurate.

EDIT: I opened a PR https://github.com/cknow/laravel-money/pull/127

**Comment by artem-zherdiev-ingio** [comment]
Hello, maintainers! Is there any news related to this issue and the proposed fix?

**Comment by mattvb91** [comment]
@ricardogobbosouza any chance you could take a look at the associated PR im experiencing the same issue

**Comment by ricardogobbosouza** [comment]
#127
