### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by hugofabricio** [cknow/laravel-money#13]
Hot to return value in string but use in json?

In my tests, return a Money Object.

**Comment by ricardogobbosouza** [comment]
Sorry for the delay!

To return JSON, you can use the `toJson` method.
For example:

```php
Money::BRL(500)->toJson();
```

**Comment by hugofabricio** [comment]
Desculpe man, não expliquei direito, estou usando ele para retornar o valor já formatado, sendo que não retorna R$ 5,00 como quando usado nas views, e sim assim:

<img width="347" alt="captura de tela 2017-05-23 as 11 10 20" src="https://cloud.githubusercontent.com/assets/425678/26358298/7ba8dddc-3fa8-11e7-8ef2-f83e4301fc55.png">

**Comment by ricardogobbosouza** [comment]
I think I understand! LOL
You can use this way:

```php
Money::BRL(500)->render();
```
or
```php
Money::BRL(500)->format();
```

**Comment by hugofabricio** [comment]
Thanks, its right!
