### ISSUE TITLE
Setting cast attribute example in readme is incorrect

### ISSUE THREAD

**Issue by andreasnij** [cknow/laravel-money#131]
In the readme file there is the following example when setting a cast attribute:

```
$model->money = 10; // 10.00 USD or any other currency defined
```

But setting `$model->money = 10;` seem to produce `0.10 USD` on the latest version (v7.0.2).

Not sure if it's the readme or the implementation that is incorrect.

**Comment by neoighodaro** [comment]
The implementation is correct, in the change log of 7.0 it mentions that there was this breaking change

**Comment by ricardogobbosouza** [comment]
Hi @andreasnij 
The readme is wrong
I will correct
Thanks
