### ISSUE TITLE
Invalid argument in NumberFormatter() 

### ISSUE THREAD

**Issue by Limman** [cknow/laravel-money#135]
Hi. After upgrading from v6 to v7 I got the following error:
```
    "class": "Money\\Exception\\UnknownCurrencyException",
    "message": "Cannot find currency 淠᎓翼",
    "code": 0,
    "file": "/var/app/test/vendor/moneyphp/money/src/Currencies/AggregateCurrencies.php:48",
    "trace": [
        "/var/app/test/vendor/moneyphp/money/src/Parser/IntlMoneyParser.php:56",
        "/var/app/test/vendor/moneyphp/money/src/Parser/AggregateMoneyParser.php:38",
        "/var/app/test/vendor/cknow/laravel-money/src/MoneyParserTrait.php:227",
        "/var/app/test/vendor/cknow/laravel-money/src/MoneyParserTrait.php:110",
        "/var/app/test/vendor/cknow/laravel-money/src/MoneyParserTrait.php:87",
        "/var/app/test/vendor/cknow/laravel-money/src/Casts/MoneyCast.php:62",
    ...
```
This problem was caused by this [change](https://github.com/cknow/laravel-money/compare/v6.4.0...v7.0.0#diff-7e752b69b3b0c93f139b8765705bd9a69b7969fe78d1ee8c5739b5862db534daR77) and reproduced if `intl` extension was built with old ICU (in my case it is 50.2). It is default version with PHP 8.1 on fresh AWS Amazon Linux 2. With ICU version 67.1 (Debian and PHP 8.1) there are no errors.

`$style` argument in [NumberFormatter()](https://www.php.net/manual/en/numberformatter.create.php) should be `int`. In v7 `$style = NumberFormatter::CURRENCY || NumberFormatter::DECIMAL` is equal to `true` and casts to `1` (it is equal to `NumberFormatter::DECIMAL`). 

The problem with `NumberFormatter()` can be reproduced on [onlinephp.io](https://onlinephp.io?s=s7EvyCjg5eLlUkkuLSpKzUuuVLBVUFe3Bgrk5uelgnmGhnqGBmCh4pLKnFSgkF9pblJqkVt-UW5iSUlqkZWVc2hQkKufc6RCTQ2mpIurs6evo4812Jq03BKgAXmp5ejqNNRT8-JDg9V1FCDWaIIsTElNzsxNzAHqAGnUtStILCpOdYa6VAPiRKAGmNs1wXaUJRbFp5TmFmigiAMA&v=8.2.0%2C8.1.13%2C8.0.26%2C8.1.12%2C8.1.11). Try to execute code few times. 
<img width="644" src="https://user-images.githubusercontent.com/9432322/209721925-00b6f4fe-8c13-44d6-a77a-5d4200470324.png">

Valid result in this case should be empty string.

**Comment by simple-hacker** [comment]
I am getting the same issue.

This issue is MoneyParseTrait.php line 77

```php
$style = NumberFormatter::CURRENCY || NumberFormatter::DECIMAL;
```

This is `2 || 1` which gets evaluated to `true`, which then casts to an int as `1` in the parser, and so both the `IntlMoneyParser` and  `IntlLocalizedDecimalParser` are using the `NumberFormatter::DECIMAL` and CURRENCY is never used.

Also there is an accounting currency value that I think would be useful to replace the CURRENCY with:

https://www.php.net/manual/en/class.numberformatter.php#numberformatter.constants.currency-accounting

**Comment by joseburgon** [comment]
I'm also affected by this issue. My PHP version: 8.1.20. Will downgrade to version 6 in the meantime.
