### ISSUE TITLE
 WARN  PHP Deprecated: Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by Johannes-Werbrouck** [cknow/laravel-money#138]
In PHP 8.2, `${var}` is deprecated and the `{$var}` notation is preferred. 

Here is mentioned that the {$var} notation is compatible across PHP versions: [PHP Watch](https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated#dollar-outside).

**Comment by ricardogobbosouza** [comment]
Resolve #132

**Comment by ricardogobbosouza** [comment]
Released [v7.1.0](https://github.com/cknow/laravel-money/releases/tag/v7.1.0)
