### ISSUE TITLE
Class "NumberFormatter" not found

### ISSUE THREAD

**Issue by khoshbin86** [cknow/laravel-money#140]
Hi, I get this error above on Laravel 9.

**Comment by Lu3kaskluge** [comment]
laravel-money uses MoneyPHP, MoneyPHP uses the NumberFormatter class, but this class is part of the "intl" library (which is NOT enabled by default).
On Windows you can try editing the php.ini file and uncomment the line "`extension=ext/php_intl.dll`"
On Linux you can install this extension with the command "`sudo apt install php8.1-intl`"

**Comment by Lu3kaskluge** [comment]
laravel-money uses MoneyPHP, MoneyPHP uses the NumberFormatter class, but this class is part of the "intl" extension (which is NOT enabled by default).
On Windows you can try editing the php.ini file and uncomment the line `extension=ext/php_intl.dll`
On Linux you can install this extension with the command `sudo apt install php8.1-intl`
