### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by ultimateBusiness** [cknow/laravel-money#142]
It's not possible to update to Laravel 10, because of missing support for it.

**Comment by neoighodaro** [comment]
@ultimateBusiness just so you know you can use #141 pending it being merged

**Comment by sbc640964** [comment]
@neoighodaro  How can I required the package from the composer with this pull request?

**Comment by ricardogobbosouza** [comment]
Released [v7.1.0](https://github.com/cknow/laravel-money/releases/tag/v7.1.0)
