### ISSUE TITLE
Laravel Money removing the last zero at the end of a price

### ISSUE THREAD

**Issue by He1senb0rg** [cknow/laravel-money#146]
Hello, I am currently developing an website in laravel, and i'm using cknow/laravel-money to display prices. The issue is, when the price ends with an zero, for example "94,90€", laravel money removes that last zero at the end, and the price is displayed like this "94,9€", and I dont want to display the prices like that.

I'm using this to display the price in my view "{{ money($produto->desconto)->format(null, null, \NumberFormatter::DECIMAL) }}€".

Hope someone can help me with this.

**Comment by omarsancas** [comment]
I have the same behaviour
`$amount = (string) 4465.60;
    $currencyCode = $this->faker->currencyCode();

    $paystubRow = new PaystubRow([
        'offer_id' => $offer->id,
        'amount' => $amount,
        'currency_code' => $currencyCode,
        'type' => $this->faker->randomElement(\App\Domain\Payees\Models\AdditionalCompensation::types()),
        'start_date' => '02/12/2023',
        'end_date' => '02/12/2023',
    ]);

    expect($paystubRow->amount->formatByDecimal())->toBe($amount);`

--- Expected
  +++ Actual
  @@ @@
  -'4465.6'
  +'4465.60'

    
    inside paystub row class
    `public function __construct($csvRow)
    {
        $this->offer = Offer::select('id')->findOrFail(strval($csvRow['offer_id']));
        $this->amount = money(strval($csvRow['amount']), $csvRow['currency_code']);`

**Comment by ricardogobbosouza** [comment]
Hi @He1senb0rg 
You can use `formatByCurrencySymbol`

```php
Money::USD(500)->format(); // $5.00
Money::USD(500)->formatByCurrencySymbol(); // $5.00
Money::USD(500)->formatByCurrencySymbol(true); // 5.00$
```
