### ISSUE TITLE
Setting cast attribute example in readme is incorrect

### ISSUE THREAD

**Issue by XaiMeS** [cknow/laravel-money#147]
Hi,
I think there is an error in this example
`$model->money = Money::EUR(10); // 10 EUR`
It produce 0.10 for me

![image](https://user-images.githubusercontent.com/36962784/230653423-25d84ede-8ff7-495d-a30c-b08ae417f142.png)

**Comment by bbashy** [comment]
Having a similar issue with validation. Can force decimals[0] on the cast part but then "100" in the input comes out as £10,000.00 when saved.

[0]
```
'money' => MoneyIntegerCast::class.':GBP,true',
```
