### ISSUE TITLE
MoneyStringCast not working with Factories

### ISSUE THREAD

**Issue by quiquegarcia** [cknow/laravel-money#148]
Hello, I think there is a bug using MoneyStringCast with Factories.

When I build my model using factories the ```currency``` attribute is ignored and the default application currency is assigned.

I have my model casts this way:

```php
use Cknow\Money\Casts\MoneyStringCast;

class Contract extends Model
{
    use HasFactory;

    protected $casts = [
        'amount' => MoneyStringCast::class . ':currency',
    ]
}
```
Where **currency** is the field that holds the currency, so when I do something like:
```php
$contract = Contract::factory(['amount' => '100000', 'currency' => 'MXN'])->create();
```
I got:
```php
App\Models\Contract {
    amount: '1000.00 US$'
    currency: 'MXN',
}
```
Instead of:
```php
App\Models\Contract {
    currency: 'MXN',
    amount: '1000.00 MXN'
}
```
But when I do the next operations, works like this:
```php
$contract = new Contract();
$contract->currency = 'MXN'; //MXN
$contract->amount = '100000'; //Cknow\Money\Money {}
$contract->amount->format(); //'1000.00 MXN'
```
There is something that I forgot or this is the spected behavior?

Thanks in advance!

**Comment by ricardogobbosouza** [comment]
Hi @quiquegarcia 
Your factory needs to contain the definition with the currency key

```php
class ContractFactory extends Factory
{
    public function definition()
    {
        return [
            'currency' => '',
        ];
    }
}
```
