### ISSUE TITLE
Format functions doesn't read precision parameter

### ISSUE THREAD

**Issue by fabiolrs** [cknow/laravel-money#15]
The format() function doesn't get the actual precision parameter from the config file, here:

`$value = number_format($amount, 2, $decimals, $thousands);`

Changing the above line to:

`$value = number_format($amount, $this->currency->getPrecision(), $decimals, $thousands);`

That correctly reads the precision parameter, which is necessary for cents fraction and different subunit values.

A nice addition would be to remove leading zeros when using precision bigger than 2, for instance, if precision is 4, showing 0,5555 is ok, but 0,5500 should still be trimmed to 0,55.

**Comment by ricardogobbosouza** [comment]
You're right! 

By the end of the week, I intend to release a new version with improvements included in laravel 5.5.
But if you want to create a PR before, I appreciate it.

Thank you.

**Comment by fabiolrs** [comment]
I'll try, no promises.

Could you please include a option to format the numbers better when using bigger than 2 precision?

I'm currently using 4 because of cents fractions (0,0499 for example), but when I get a 0,04 it formats it to 0,0400. It would be nice to, when using larger precision, trim all the leading zeros, so fractioned values would be printed 0,059494 but values with zeros like 0,01000000 would still be printed 0,01.

Té mais e valeu pelo software <3

**Comment by bosz** [comment]
Thanks you @fabiolrs , this has been giving nightmare. 
`$value = number_format($amount, $this->currency->getPrecision(), $decimals, $thousands);` worked for me well. Will be waiting for the updates to handle this so that i won't have to go editing the package every time i deploy. 

Thanks

**Comment by fabiolrs** [comment]
Hey @bosz, what do you think of my idea of having an option to pretty print the currency when it ends with lots of zeros?

I mean, we could have something on the config file to enable trimming the extra zeros, so when we use lets say a 6 digit precision, it can show 0.5 instead of 0.500000, but continue showing 0.123456 when necessary.

**Comment by ricardogobbosouza** [comment]
## New version v2.0.0!
Do not use anymore `number_format`, now require `ext_intl`.

```php
use Cknow/Money;

Money::BRL(100); // R$1,00
Money::BRL(100)->formatSimple(); // 1.00
