### ISSUE TITLE
Question: formatter with separators but without currency

### ISSUE THREAD

**Issue by ndberg** [cknow/laravel-money#154]
Thanks for this package.

Question, Is there a way to format a Number like this: `4’500.00` (searched, but couldn't find)

My Result should be with decimal AND thousands separator, but without currency.

If I Use ==> I get:
`$money->formatByIntlLocalizedDecimal() ==> CHF 4’500.00`
`$money->formatByDecimal() ==> 4500.00`

Or do I have to make an own formatter?

**Comment by ndberg** [comment]
Thanks @ricardogobbosouza for reaching back to me. 

What I need is CHF in de_CH:

`Money::CHF(10)->format(locale: 'de_CH')`

**Comment by ricardogobbosouza** [comment]
https://github.com/cknow/laravel-money/issues/155
