### ISSUE TITLE
£ should not have a space after it

### ISSUE THREAD

**Issue by jezmck** [cknow/laravel-money#16]
In the UK, we don't put a space after the pound sign.

Looking at the code, the only way to make this configurable would be to remove the hardcoded space in [getPrefix()](https://github.com/cknow/laravel-money/blob/d7e399887d76b1dae87fa2d254e25dc1b0fde966/src/ClickNow/Money/Currency.php#L411) and make the space part of the prefix strings.

**Comment by bosz** [comment]
XAF does not have space and I need space between the amount and the currency.

**Comment by ricardogobbosouza** [comment]
## New version v2.0.0!

Now required `ext_intl` to use `NumberFormatter` to format correct.

Take a look, thank you!

**Comment by jezmck** [comment]
Oh, that doesn't seem like a solution to me.

Is there any other way?

**Comment by ricardogobbosouza** [comment]
@jezmck 
Could you give me an example?
