### ISSUE TITLE
Macros not registering

### ISSUE THREAD

**Issue by liamjoc** [cknow/laravel-money#161]
I have registered the following macro in AppServiceProvider boot method.

```php
Cknow\Money\Money::macro('display', function () {
   return 'hello world';
});


echo Cknow\Money\Money::display(); // expect to see 'hello world'
```

Nothing happens and I also get the following warning...

`PHP Warning:  Undefined array key 0 in /Users/liamoconnor/Projects/x/vendor/cknow/laravel-money/src/MoneyFactory.php on line 199`

**Comment by ricardogobbosouza** [comment]
HI @liamjoc 
You need to initialize the class, in:
```php
Cknow\Money\Money::USD()->display();
```

**Comment by ricardogobbosouza** [comment]
I will add macros in the static call too
