### ISSUE TITLE
Set/change currency after the object is created?

### ISSUE THREAD

**Issue by seabasss** [cknow/laravel-money#163]
Is it possible to set the currency after the object is created? It seems like I can only cast a money object to a certain currency (and maybe that’s how it has to work), but I store what currency that I want to use on a different model and trying to figure out if I can apply the currency to the casted object after it’s created. How do you solve this in the best way? Can I use $this->model->currency in the casts property?

Thanks!

**Comment by ricardogobbosouza** [comment]
Hi @seabasss 

Today it is not possible to change the currency after the object is created.
I recommend recreating the object with the new currency.

I will analyze the need to recreate the object with a new currency by adding a new `setCurrency` function.
Ex: `Money::USD(100)->setCurrency('BRL')`
