### ISSUE TITLE
Tag release for PHP 8.4 support

### ISSUE THREAD

**Issue by SanderMuller** [cknow/laravel-money#167]
Hi, I see that PHP 8.4 support is added on the main branch, could this be tagged as a release?

I've started preparing my applications for PHP 8.4 support, and this package is generating deprecation warnings which are fixed by the main branch.

Thanks in advance!

**Comment by MasterRO94** [comment]
+1 here
I've already update my app to PHP 8.4 and go some deprecations from the package already fixed in `main` branch

**Comment by ricardogobbosouza** [comment]
I will add support for php 8.4

**Comment by ricardogobbosouza** [comment]
Hi @MasterRO94, @SanderMuller  can share deprecations?

**Comment by ricardogobbosouza** [comment]
https://github.com/cknow/laravel-money/releases/tag/v8.2.0
