### ISSUE TITLE
Should ISOCurrencies@loadCurrencies use money.isoCurrenciesPath?

### ISSUE THREAD

**Issue by alfonsogarza** [cknow/laravel-money#169]
Would it be ideal/possible to use the config at `money.isoCurrenciesPath` to swap the iso currencies list in `ISOCurrencies@loadCurrencies`?

`CurrenciesTrait@getISOCurrencies` already does it but `ISOCurrencies@loadCurrencies` has its own logic that does not use the config

Happy to submit a PR if it sounds good

**Comment by alfonsogarza** [comment]
Obrigado @ricardogobbosouza!

**Comment by negoziator** [comment]
Just if anyone comes by and it can help 😄 

If anyone encounters `"Failed to load currency ISO codes"`

Can be fixed by including the path to `currency.php` in your `money.php` config. 🎉 

```php
// config/money.php
'isoCurrenciesPath' => __DIR__.'/../vendor/moneyphp/money/resources/currency.php',
```

**Comment by SanderMuller** [comment]
> Just if anyone comes by and it can help 😄
> 
> If anyone encounters `"Failed to load currency ISO codes"`
> 
> Can be fixed by including the path to `currency.php` in your `money.php` config. 🎉
> 
> ```
> // config/money.php
> 'isoCurrenciesPath' => __DIR__.'/../vendor/moneyphp/money/resources/currency.php',
> ```

Thanks, this helped!

**Comment by ricardogobbosouza** [comment]
Hi @SanderMuller 
Sorry, the file path is wrong

**Comment by SanderMuller** [comment]
> Hi @SanderMuller Sorry, the file path is wrong

Thanks for the quick fix!
