### ISSUE TITLE
parsing of $5,555.95

### ISSUE THREAD

**Issue by dingman** [cknow/laravel-money#18]
I'm trying to parse and normalize for db storage a value of "$5,555.95" to parse that into 5555.95

I tried many variations of `money('$5,555.95','USD')->parse()` (Based on what I was reading from moneyphp docs), but it continues to through an error:

  [InvalidArgumentException]
  Invalid integer part $5,555. Invalid digit found

Any suggestions how to resolve this?

**Comment by ricardogobbosouza** [comment]
Hi @dingman,
Parse functionality has not been deployed. I'll run to get it fixed as soon as possible.
At the moment you will have to create something like this:

```php
use Money\Currencies\ISOCurrencies;
use Money\Parser\IntlMoneyParser;

$currencies = new ISOCurrencies();

$numberFormatter = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY);
$moneyParser = new IntlMoneyParser($numberFormatter, $currencies);

$money = $moneyParser->parse('$1.00');

echo $money->getAmount(); // outputs 100
```

Actually I forgot her, sorry! =/

**Comment by ricardogobbosouza** [comment]
Hi @dingman.
In the new version v2.2.0 the `parse` functionality was implemented. ex:

```php
Cknow\Money\Money::parse('$5.00');
money_parse('$5.00'); // helper
@money_parse('$5.00') // blade directive
```
Thanks

**Comment by dingman** [comment]
Thank you @ricardogobbosouza !
