### ISSUE TITLE
Invalid subunits

### ISSUE THREAD

**Issue by canfiax** [cknow/laravel-money#2]
I have discovered that some currencies have invalid subunit, for instance JPY is set to subunit "100" but should be "1".

Acording to Stripe, theese currencies are zero_decimal currencies that should have a subunit of 1:

https://support.stripe.com/questions/which-zero-decimal-currencies-does-stripe-support

**Comment by ricardogobbosouza** [comment]
Please upgrade to new version 1.8 `composer update`.
Extension `ext-intl` now is optional
Thanks

**Comment by canfiax** [comment]
Nice!
