### ISSUE TITLE
formatByFormatter

### ISSUE THREAD

**Issue by slakbal** [cknow/laravel-money#20]
Hi,

Can you maybe please add an example to the docs of how to work with a formatter be used with the "formatByFormatter" method? Can a custom formatter be defined?

1) All the currencies are against the value so on a table with lots of data it makes it hard to read.

CA$6,010,873.71

It would already help if a space could be inserted eg.

CA$ 6,010,873.71

2) is there a way to format the value to be just:

6,010,873.71

when using the formatByDecimal() the values are formatted like:

6010873.71

Thanks for the package!

**Comment by ricardogobbosouza** [comment]
Hi @slakbal ,

In version 2.3.0 an option was added to modify the formatting style and also the documentation was updated to create its own formatter.

Thanks

**Comment by ricardogobbosouza** [comment]
It helps?
