### ISSUE TITLE
How to parse correctly?

### ISSUE THREAD

**Issue by grantholle** [cknow/laravel-money#21]
I'm trying to use the helper from the readme, `money_parse('R$5,00')`, and I get `InvalidArgumentException with message 'Currency code should be string'`.

How do I use the parse functionality?

**Comment by ricardogobbosouza** [comment]
Hi @grantholle,

The form of use is correct, it works for me!

**composer.json**
```json
{
    "name":"test",
    "require": {
        "cknow/laravel-money": "^2.3"
    }
}
```

**test.php**
```php
require "vendor/autoload.php";

echo money_parse("R$5,00");
```

Could you give me an example?

**Comment by ricardogobbosouza** [comment]
Hi @grantholle 

In laravel, `mone_parse` it depends locale in `config/app.php` which default is `en`

```php
@money_parse('$6.00')
@money_parse('R$7,00', null, 'pt_BR')
@money_parse('R$8,00', null, 'pt_BR')
```

**Comment by grantholle** [comment]
It was my bad! My php version was messed up so I didn't end up having intl installed right... Sorry for the pointless bug 😭
