### ISSUE TITLE
When serialized by laravel the formatted amount with currency symbol dissappears

### ISSUE THREAD

**Issue by greaterking** [cknow/laravel-money#22]
When using this amazing package when ever I return my amount as a money object as json I only ever get..

{amount: "29000", currency: "USD"}

I would also like to get the format with the actual currency symbol i.e. $29.00 so it could return

{amount: "29000", currency: "USD", formatted: "$29.00"} 

Forgive me if i'm not using the package correctly.

**Comment by ricardogobbosouza** [comment]
Hi @greaterking,

You're right!  Currently the return is
```json
{"amount": "29000", "currency": "USD"}
```
In the new version I will implement this improvement
```json
{"amount": "29000", "currency": "USD", "formatted": "$29.00"}
```

Soon I will launch this new improvement and with the new version of  `MoneyPHP@3.1.0`

Thanks

**Comment by greaterking** [comment]
@ricardogobbosouza Thank you so much an thank you for the fast response! Another a small suggestion would be that it may be beneficial to some to have the ability to possibly set their own properties as well. I say this because in many applications using json as return you may want some custom data like
```
{
    "amount": "29000", 
    "currency": "USD", 
    "formatted": "$29.00", 
    "convertsions": [
        {"amount": "19000", "currency": "BRL", "formatted": "$19.00"},
        {"amount": "2000", "currency": "EUR", "formatted": "$2.00"},
        {"amount": "77000", "currency": "DZD", "formatted": "$77.00"}
     ]
}
```
Be the default perhaps we can hook into the serialization some how. I have no real knowledge of your code. But in laravel I know you can customize what type of data is retrieved in json during serialization. 

It would be great if we can set our own properties that we need ...for example if I wanted a property called "converted" to be part of that json that would be great. I was trying this before in my model which is why I reached out to you and when serialized it never showed

```
public function getFormattedAmountAttribute()
{
      $money = Money::USD($this->amount);
      $money->formatted  = $money->render(); // the "formatted" never shows in json
      return $money;
}
```

Sorry not trying to burden you .. very happy with the upcoming changes but just wanted to suggest.

**Comment by ricardogobbosouza** [comment]
Hi @greaterking,
I just implemented these improvements!

Now when serializing the result it contains `formatted`
```json
{"amount": "29000", "currency": "USD", "formatted": "$29.00"}
```

I also added the method `attributes` to custom serialize, see:

```php
$money = Money::BRL(10);
$money->attributes(['key' => 'value'])
return $money;
```
result:
```json
{"amount": "29000", "currency": "USD", "formatted": "$29.00", "key": "value"}
```

Thanks

**Comment by greaterking** [comment]
Amazing!!! Stellar support brother... problem solved..and them some 😄 !
