### ISSUE TITLE
How to change default locale?

### ISSUE THREAD

**Issue by dbrw** [cknow/laravel-money#27]
I tried to change locale in `config/app.php` but `Money($amount)` still returned BRL as it's currency.

Any possible method?

**Comment by ricardogobbosouza** [comment]
Hi @dbrw,
You can change locale in`config/app.php` on property `locale`.
If you want to change a currency, you can use `Money::USD`  for example or `Money::EUR`, among others.
If not, please explain the problem in more detail.

**Comment by dbrw** [comment]
Just to clarify, I put lets say `'locale' => 'id',` on my `config/app.php`, but I still got BRL as default currency.

I think moneyphp wants different country code format than laravel. As for work around, I created another key on config like `'currency' => 'IDR',` and `Money::setLocale(config('app.currency'))` on app service provider.

It would be nice if we can use default laravel country code with this wonderful package.

**Comment by ricardogobbosouza** [comment]
Hi @dbrw,

I just launched a version where you can change both the default locale and the currency.
Please take a look at the updated documentation, i believe this will solve the problem.

Thanks

**Comment by dbrw** [comment]
Nice!
Thank you so much!
