### ISSUE TITLE
Config and Blade Extensions not working

### ISSUE THREAD

**Issue by GiacomoK** [cknow/laravel-money#29]
Hi,  
I correctly installed the package, but I have these errors:
This is my config/money.php:

    'locale' => 'it_IT',
    'currency' => 'EUR',

but I always get the dollar symbol if I use `money(value)` in blade file.

Other than that, in blade file `@money(value)` does not work.

**Comment by ricardogobbosouza** [comment]
Hi @GiacomoK,
Is it working for me, could you give me more details?
Is the package version up to date?

**Comment by GiacomoK** [comment]
intl is installed.  
 Is it possibile that italian language is not installed on the server?

**Comment by ricardogobbosouza** [comment]
How it is displayed to you?

Following these steps:

```
composer global require "laravel/installer"
laravel new money
cd money
composer require cknow/laravel-money
php artisan vendor:publish --provider="Cknow\Money\MoneyServiceProvider"
php artisan serve
```
change `config/money.php`
```php
<?php

return [
    /*
     |--------------------------------------------------------------------------
     | Laravel money
     |--------------------------------------------------------------------------
     */
    'locale' => 'it_IT',
    'currency' => 'EUR',
];
```
In `resources/views/welcome.php`
```php
@money(500)
```
You should see: **5,00 €**

**Comment by ricardogobbosouza** [comment]
@GiacomoK can close this?

**Comment by ricardogobbosouza** [comment]
@whollaus You're not counting the cents.

**Comment by ricardogobbosouza** [comment]
To show 500,00 €
`@money(50000, 'EUR')`

**Comment by whollaus** [comment]
But that's not logical ;)
I have five hundred euros = 500 = 500,00 €
5,00 € are only five euros

nobody saves in a database 50000 for 500 
ok, this is an moneyphp problem...

**Comment by ricardogobbosouza** [comment]
You're not thinking about the cents.

**Comment by whollaus** [comment]
Normally it's done like this:
![grafik](https://user-images.githubusercontent.com/4582757/53158784-b6e78880-35c4-11e9-996d-c0d8eb105a57.png)
http://openexchangerates.github.io/accounting.js/#demo

or look here:
https://www.evertype.com/standards/euro/formats.html

This class only works (for me) if i first multiply with 100. In the database I have numbers like this: 500.58 or 35.7. The result should be 500,58 € or 35,70 €

**Comment by ricardogobbosouza** [comment]
See http://moneyphp.org/en/stable/#why-a-money-library-for-php
