### ISSUE TITLE
AWESOME project - but how do I round up/down?

### ISSUE THREAD

**Issue by canfiax** [cknow/laravel-money#3]
I would like to round up / down, instead of getting formats such as: $67,32. How?

**Comment by ricardogobbosouza** [comment]
Deixa eu ver se entendi...
Você gostatia de arredondar $67,32 para $67 ?

**Comment by ricardogobbosouza** [comment]
Let me see if I got it ...
You gostatia quick round of paragraph $ 67.32 $ 67 ?

**Comment by ricardogobbosouza** [comment]
Let me see if I got it ...
Would you like to round up $ 67.32 to $ 67 ?

**Comment by canfiax** [comment]
Yes
