### ISSUE TITLE
IntlLocalizedDecimalParser

### ISSUE THREAD

**Issue by stelgenhof** [cknow/laravel-money#30]
Thanks for the great package!

One thing I noticed is that parsing using the 'IntlLocalizedDecimalParser' from the Money package isn't implemented. Any particular reason why that is? 

For me would be beneficial to have this, as I have to deal with localized decimal numbers that represents a monetary value but don't have any currency symbol. At the moment I'm using the `parseByDecimal` method, however doesn't always work when decimal numbers have a comma for representing the decimal point.

Cheers! Sacha

**Comment by ricardogobbosouza** [comment]
Hi @stelgenhof

There is no particular reason. Not all parses have been implemented, there may be several, but there is the `parseByParser` method.

Try this:

```php
use Cknow\Money;

$nf = new \NumberFormatter(Money::getLocale(), \NumberFormatter::CURRENCY);
$parser = new \Money\Parser\IntlLocalizedDecimalParser($nf, Money::getCurrencies());

$money = Money::parseByParser($parser, 5000);
```

I will analyze the need of the other  #parses, to make it easier :smiley:

**Comment by stelgenhof** [comment]
@ricardogobbosouza Thanks for the quick response!

Yes, I did exactly the same as you suggested. It works perfectly. However I was just wondering if it could be implemented as part of the package. Not super urgent though :)

Cheers! Sacha

**Comment by ricardogobbosouza** [comment]
Hi @stelgenhof
I just released a version with these new features :smile: 

https://github.com/cknow/laravel-money/releases/tag/v3.3.0

**Comment by stelgenhof** [comment]
Super!
