### ISSUE TITLE
symbol_first no longer in v3

### ISSUE THREAD

**Issue by bosz** [cknow/laravel-money#32]
Hi, I have been using this package since it was at version 1, 
In version 1, `"cknow/laravel-money": "^1.0",`, the vendor publish generated a config file, `config/clicknow.money.php` that had something like so 
```
'XAF' => [
        'name'                => 'CFA Franc BEAC',
        'code'                => 950,
        'precision'           => 0,
        'subunit'             => 1,
        'symbol'              => ' FCFA',
        'symbol_first'        => false,
        'decimal_mark'        => '.',
        'thousands_separator' => ',',
    ],
```

But the current version, `"cknow/laravel-money": "^3.4",` which am using does not have that again in the config, `config/money.php`, 

All i want is to be able to set the option where the currency comes one space after the amount, 

Rather than having FCFA1,200 , i want to have 1,200 FCFA , 

Is there an option to do this please, 

BTW, awesome package you got there, i love it.

**Comment by ricardogobbosouza** [comment]
Hi @bosz 

In the current version we use the pactore [MoneyPHP](http://moneyphp.org) with that we no longer have these configurations.

You can create your own formatter, if the format default does not suit your needs
https://github.com/cknow/laravel-money#create-your-formatter
