### ISSUE TITLE
XBT currency not exists in this repository

### ISSUE THREAD

**Issue by SerGioPicconti** [cknow/laravel-money#37]
Hi
I need to use XBT currency, but when I set in config currency to XBT I get error that xbt is not supported by current repository.
Do I need to change something to use xbt?

**Comment by SerGioPicconti** [comment]
Exception log message:
`Cannot find ISO currency XBT at /vendor/moneyphp/money/src/Currencies/ISOCurrencies.php:37`

**Comment by ricardogobbosouza** [comment]
Hi @SerGioPicconti 
Can you show the code?

**Comment by SerGioPicconti** [comment]
Hi)
It’s simple - Money::XBT($amount);

**Comment by SerGioPicconti** [comment]
As I understand it’s because XBT is not in ISO currency list)

**Comment by SerGioPicconti** [comment]
One thing - I use Money in model mutation.
And then in logic

**Comment by SerGioPicconti** [comment]
It working if I set currency in service provider via currency aggregating (iso and bitcoin), but formatter still work wrong - it use 2 point decimals

**Comment by ricardogobbosouza** [comment]
Yes, XBT is https://github.com/moneyphp/money/blob/master/src/Currencies/BitcoinCurrencies.php#L14

**Comment by SerGioPicconti** [comment]
So if amount is about 0.0004 btc (for example) - in formatted value it shows «0.00 XBT”

**Comment by SerGioPicconti** [comment]
Yes I have found it, but I wanted to know what is the right way to aggregate iso and bitcoin currencies?
In service provider Money::setCurrency($array)?
Or any other way?

**Comment by ricardogobbosouza** [comment]
You can use `formatByBitcoin` https://github.com/cknow/laravel-money/blob/master/src/MoneyFormatterTrait.php#L53

`Money::XBT($amount)->formatByBitcoin(4)`

**Comment by ricardogobbosouza** [comment]
@SerGioPicconti works?

**Comment by SerGioPicconti** [comment]
I’ll try it little bit later
In a few hours
Pm you) thx)

**Comment by ricardogobbosouza** [comment]
Ok. Bitcoin is a different currency

**Comment by ricardogobbosouza** [comment]
Can close?

**Comment by ricardogobbosouza** [comment]
@SerGioPicconti Can close?

**Comment by SerGioPicconti** [comment]
> @SerGioPicconti can close?

Yep) Figure out everything)

**Comment by SerGioPicconti** [comment]
thx))

**Comment by ricardogobbosouza** [comment]
:smile:
