### ISSUE TITLE
Make `\Cknow\Money\Money` object from `\Money\Money` object

### ISSUE THREAD

**Issue by atymic** [cknow/laravel-money#45]
I plan to do a PR for #19, but it the mean time i'm using the conversion features from moneyPHP directly. 

The issue is that they return a `Money\Money` object, which breaks the downstream    type hints for `\Cknow\Money\Money`.

I propose to add a static constructor that returns an instance of this library's class from the base money object. That way, I can massage it back to the right type :)

```
\Cknow\Money\Money::fromMoney(\Money\Money $money): \Cknow\Money\Money
```

Will PR shortly if that's ok :)

**Comment by ricardogobbosouza** [comment]
Hi @atymic 
Sorry for the late answer

You can use the `convert` method
https://github.com/cknow/laravel-money/blob/master/src/Money.php#L117

**Comment by atymic** [comment]
Oops, don't know how I missed that!
Closing this :P
