### ISSUE TITLE
ReflectionException - Class blade.compiler does not exist - L5.2

### ISSUE THREAD

**Issue by nunomazer** [cknow/laravel-money#5]
Hi, I'm receiving this error on Laravel 5.2

Resolved by registering BladeExtensions at MoneyServiceProvider with the following line

    BladeExtensions::register(app('view')->getEngineResolver()->resolve('blade')->getCompiler());

Do you want me to create a pull request for this?

**Comment by ricardogobbosouza** [comment]
Fixed, Thanks =)
