### ISSUE TITLE
Incorrect output for IRR currency

### ISSUE THREAD

**Issue by Mdhesari** [cknow/laravel-money#51]
with USA currency everything works well until it is changed to other currencies like IRR,

we can call it poor support for other currencies.

![image](https://user-images.githubusercontent.com/28428724/76348545-9bf5cc80-631d-11ea-8a30-6dd05794993e.png)

**Comment by ricardogobbosouza** [comment]
Hi @Mdhesari 
I am not aware of all currencies, so we use the library https://github.com/moneyphp/money
Remembering that you can create your own formatter https://github.com/cknow/laravel-money#create-your-formatter
