### ISSUE TITLE
Trait method conflict

### ISSUE THREAD

**Issue by cerbero90** [cknow/laravel-money#54]
There is currently an issue when trying to retrieve the currency from a `Cknow\Money\Money` instance:

```php
$money = new Money('100', new Currency('EUR'));

return $money->getCurrency();
```

The expected returning value would be an instance of `Money\Currency` holding `EUR` as currency code. However we get the string `USD` because `CurrenciesTrait::getCurrency()` is called instead.

**Comment by ricardogobbosouza** [comment]
@cerbero90 
For that we need to use `getMoney`

```php
$money = new Money('100', new Currency('EUR'));

return $money->getMoney()->getCurrency();
```

Any other suggestions?

**Comment by cerbero90** [comment]
My concern is that it might lead to errors as the user would probably expect to get the currency of the Money instance as the method suggests (I fell in that trap myself).

What do you think about renaming the methods of the `CurrenciesTrait`? This might be part of the changes introduced in the major version bump caused by the Laravel 7 custom cast feature.
