### ISSUE TITLE
Strange output with seperators

### ISSUE THREAD

**Issue by simplenotezy** [cknow/laravel-money#6]
I get very strange output depending on what seperator I use. See:

```
money('1', 'DKK', true)->getAmount() // returns '100' (ØRE) as expected
money('1,5', 'DKK', true)->getAmount() // returns '150' (ØRE) as expected
money('1.5', 'DKK', true)->getAmount() // returns '1500' -> unexpected.
```

I guess this is because of the thousand separator, but it seems like a bug to me.

**Comment by ricardogobbosouza** [comment]
Sorry for the delay
I will try to improve the conversion so that the separator thousand is always multiplied.
But the correct thing:
```
money ('1.500' 'DKK', true);
```
Sorry my bad english

**Comment by simplenotezy** [comment]
Thanks!
