### ISSUE TITLE
Idea: attributes for currency extraction from database

### ISSUE THREAD

**Issue by sergotail** [cknow/laravel-money#60]
When currency is stored in database in two columns:
1) amount
2) currency (or currency code, e.g. 810 for RUB)

It would be nice to add capability to specify from which attributes currency will be casted. It can be implemented via `$attributes` param for `CastsAttributes::get` and` CastsAttributes::set` methods. For example, user can extend `MoneyCast` class and redefine such attributes to desired.

**Comment by ricardogobbosouza** [comment]
This is already possible on v5

https://github.com/cknow/laravel-money#casts
