### ISSUE TITLE
Breaks package discovery on App Engine

### ISSUE THREAD

**Issue by JasonTheAdams** [cknow/laravel-money#61]
Greetings!

First, thanks for putting this together. It really cleans up MoneyPHP and makes a nice, uniform way of working with it in Laravel.

After _much_ debugging, I've narrowed down a deployment failure to [App Engine](https://www.google.com/search?q=app+engine&oq=app+engine&aqs=chrome..69i57j0l4j69i60l2j69i61.1986j0j7&sourceid=chrome&ie=UTF-8) as a failure of `php artisan package:discover --ansi` during the build process. If I remove this package, then the deployment works just fine.

The best I can tell from the build failure output is this hunk:
```
Step #1 - "builder": In Compiler.php line 36:
Step #1 - "builder":                                       
Step #1 - "builder":   Please provide a valid cache path.  
```

Please keep in mind that this _only_ occurs if this package is installed. If I remove the package, then this error does not occur. This makes me think that this package is attempting to access something from the cache _before_ things are ready.

This may have something to do with how App Engine introduces environment variables. In a normal Laravel setup the `.env` file provides the environment data and is loaded in, then accessible via the `env`. App Engine, conversely, has an `app.yaml` file that loads data as _environment variables_ — rather than being loaded upfront. This still works, however, as the `env` function checks for environment variables as well.

If I find anything further I'll be sure to add a comment.

**Comment by JasonTheAdams** [comment]
I'm suspicious of this line: https://github.com/cknow/laravel-money/blob/master/src/MoneyServiceProvider.php#L20

The `Please provide a valid cache path` error has to do with the view compiler.

**Comment by cpraught** [comment]
Hey Jason,

I had this problem too. I've solved it temporarily by downgrading to v4.0.0, which installs successfully.

**Comment by JasonTheAdams** [comment]
Oh, that's interesting, so clearly something changed between 4.x and 5.x. I'm curious what that was. 

Thanks for pointing that out, @cpraught!

**Comment by ricardogobbosouza** [comment]
Hi @JasonTheAdams , @cpraught 
Thanks for reporting.
From version 4 to 5 the settings have been modified, did you update?

Anyway, I will make compatibility with previous versions

**Comment by ricardogobbosouza** [comment]
Sorry for the late reply

**Comment by cpraught** [comment]
I first tried a clean install of v5. When that didn't work, I tried v4 and it installed fine.

**Comment by ricardogobbosouza** [comment]
Hi @JasonTheAdams, @cpraught
Fixed on v5.0.1

**Comment by JasonTheAdams** [comment]
Thanks, @ricardogobbosouza! Out of curiosity, what was the problem? It wasn't evident to me by looking at the PR.

**Comment by ricardogobbosouza** [comment]
Hi @JasonTheAdams 

The `money.currencies` setting did not exist in previous versions.
And if the user has not updated the settings https://github.com/cknow/laravel-money#configuration
the method `setCurrencies` fail https://github.com/cknow/laravel-money/pull/65/files#diff-fccd8119c71e8cdaa0fafc6183bee36dL68
So the application does not booted.

I hope I clarified, lol
