### ISSUE TITLE
MoneyCast uses the decimal formatter.

### ISSUE THREAD

**Issue by kevinruscoe** [cknow/laravel-money#62]
I was under the impression that money values should be stored in the database as VARCHAR to help with float rounding issues.

With that, the MoneyCast class seems use the DecimalFormatter to cast values to Money objects  https://github.com/cknow/laravel-money/blob/master/src/MoneyCast.php#L44.

Shouldn't this use the normal formatter? Perhaps we could get the value, and if it doesn't contain a ".", use the normal formatter? So values like 1000 become $10.00.

**Comment by pristavu** [comment]
MoneyCast works only if we use decimal field $table->decimal('money', 15, 2) 
As @kevinruscoe said earlier, the essence is to save varchar or integer values in the database. 

$model->money = 10;  (the value stored in db is '10.00')
$model->money = '10';  (the value stored in the db is '0.10')
$model->money = 10.30; (the value stored in db is '10.30' )
$model->money = '10.30'; (this fails (Invalid data provided))

"Monetary calculations are often rounded to the smallest currency unit. When you do this it’s easy to lose pennies (or your local equivalent) because of rounding errors."

**Comment by kevinruscoe** [comment]
Maybe the simplies soution is just a config option telling laravel-money _how_ you store your money? Using that in the MoneyCast class to properly serialise/deserialise the values?

**Comment by patrickomeara** [comment]
`MoneyCast` expecting a different format to `parse()` is a little confusing. 
Different casts would probably be clearer, `MoneyIntCast`, `MoneyStringCast`, `MoneyDecimalCast` these could extend an abstract class to utilise `getCurrency()`

@atymic @cerbero90 I assume you are persisting decimal in the database using `MoneyCast`. Your thoughts on the different casts above would be appreciated.

Alternatively, a config option as @kevinruscoe has mentioned would also work. I'm happy to get PRs together for both options.

**Comment by kevinruscoe** [comment]
I think your suggestion is best, having multiple cast classes. I dunno what I was drinking when I suggested changing the functionality based on the config, it just isn't obviosuly whats going on unless you dig into the code then eveually see it's look for config options.

**Comment by iamroi** [comment]
@patrickomeara @kevinruscoe thanks for the suggestion! I have made a quick gist for [MoneyIntCast](https://gist.github.com/iamroi/f87e328994dc821667b7ee87244f9cf3). It would be great to have it part of the package.

**Comment by Skullbock** [comment]
I made a PR to add this money int cast support ;)

**Comment by Skullbock** [comment]
@ricardogobbosouza do you have any news on this issue and the related pr #74 ?

Thanks!

**Comment by ricardogobbosouza** [comment]
Hi @Skullbock 

I need to refactor this PR and correct the possible problems, I'll try to do that tomorrow

**Comment by Skullbock** [comment]
No hurry! Let me know if I can help in any way

**Comment by keenminded** [comment]
Waiting for this. Thank you for the great package and the support, everyone!

**Comment by perstnev** [comment]
Any chance of moving this change into the package?

**Comment by Skullbock** [comment]
@ricardogobbosouza if needed i can provide some refactoring

**Comment by ricardogobbosouza** [comment]
Sorry for the delay, I will analyze this week

**Comment by ricardogobbosouza** [comment]
@Skullbock, @patrickomeara 
Your opinion is welcome =)
https://github.com/cknow/laravel-money/pull/90

**Comment by Skullbock** [comment]
@ricardogobbosouza seems very good, love the "ineroperability"

Very clear imho
```php
        static::assertEquals(Money::parse('100.00', 'USD'), Money::USD(10000));
        static::assertEquals(Money::parse('$1.00'), Money::USD(100));
        static::assertEquals(Money::parse('$1.00', 'USD'), Money::USD(100));
        static::assertEquals(Money::parse(1, 'USD'), Money::USD(1));
        static::assertEquals(Money::parse(1.10, 'USD'), Money::USD(110));
        static::assertEquals(Money::parse('100', 'USD'), Money::USD(100));
        static::assertEquals(Money::parse('1', 'USD'), Money::USD(1));
        static::assertEquals(Money::parse(Money::USD(100)), Money::USD(100));
        static::assertEquals(Money::parse(new \Money\Money(100, new Currency('USD'))), Money::USD(100));
```

**Comment by patrickomeara** [comment]
@ricardogobbosouza Looks like a great addition to the package.
