### ISSUE TITLE
Error trying to install Laravel 7

### ISSUE THREAD

**Issue by thetoad01** [cknow/laravel-money#63]
TypeError

Argument 1 passed to Akaunting\Money\Currency::setCurrencies() must be of the type array, null given, called in C:\websites\laravel-tests\vendor\akaunting\money\src\Provider.php on line 22

at C:\websites\laravel-tests\vendor\akaunting\money\src\Currency.php:279
    275|      * @param array $currencies
    276|      *
    277|      * @return void
    278|      */
  > 279|     public static function setCurrencies(array $currencies)
    280|     {
    281|         static::$currencies = $currencies;
    282|     }
    283|

1   C:\websites\laravel-tests\vendor\akaunting\money\src\Provider.php:22
      Akaunting\Money\Currency::setCurrencies()

2   C:\websites\laravel-tests\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:33
      Akaunting\Money\Provider::boot()

**Comment by ricardogobbosouza** [comment]
Hi @thetoad01 
This is not my package
