### ISSUE TITLE
Error trying to install Laravel 7

### ISSUE THREAD

**Issue by thetoad01** [cknow/laravel-money#64]
InvalidArgumentException

  $currencies must be an array or a \Money\Currencies object

  at C:\websites\new1\vendor\cknow\laravel-money\src\CurrenciesTrait.php:82
    78|
    79|             return;
    80|         }
    81|
  > 82|         throw new InvalidArgumentException(
    83|             '$currencies must be an array or a \Money\Currencies object'
    84|         );
    85|     }
    86|

  1   C:\websites\new1\vendor\cknow\laravel-money\src\MoneyServiceProvider.php:25
      Cknow\Money\Money::setCurrencies()

  2   C:\websites\new1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:33
      Cknow\Money\MoneyServiceProvider::boot()

**Comment by ricardogobbosouza** [comment]
Hi @thetoad01 
Thanks for reporting.
From version 4 to 5 the settings have been modified, did you update?

Anyway, I will make compatibility with previous versions

**Comment by thetoad01** [comment]
The project was originally created with 5.5 and has been updated regularly.

PS C:\websites\new1> php artisan
Laravel Framework 7.18.0

**Comment by ricardogobbosouza** [comment]
Hi @thetoad01 
Fixed on v5.0.1

**Comment by thetoad01** [comment]
Nice!  I'll have to look at what you did.  I'm getting a similar error with something else.
