### ISSUE TITLE
How to change or disable symbol in blade

### ISSUE THREAD

**Issue by roarkmccolgan** [cknow/laravel-money#66]
Hi,

Thank you for the awesome package.

In south Africa our currency is ZAR (Rand), however we display pricing like this: R100.00 and not ZAR100.00

Using blade, how do I force the symbol 'R' or just return the decimal value so I can add the 'R' myself?

Thanks!

**Comment by ricardogobbosouza** [comment]
Hi @roarkmccolgan 
You can do this:
```php
{{ money(500)->formatSimple() }}
```

**Comment by roarkmccolgan** [comment]
Awesome! Thank you
