### ISSUE TITLE
Where does the default currency come from?

### ISSUE THREAD

**Issue by aerni** [cknow/laravel-money#69]
I'm integrating this package within another Laravel package I'm working on. I don't want the user to manage two config files. So I'm setting the config for laravel-money from within my package's service provider. This works great.

```php
protected function setMoneyConfig(): void
{
    $locale = Config::get('my_package.locale');
    $currency = Config::get('my_package.currency');

    Config::set('money.locale', $locale);
    Config::set('money.defaultCurrency', $currency);
}
```

I tried the `money()` helper. According to the config if should use the default currency set in the config.

```php
money(500); // To use default currency present in `config/money.php`
```

But `money(500)->currency()` still returns `USD`. I'm expecting it to return the currency I set in my service provider. So now I'm not quite sure if everything works properly under the hood.

**Comment by ricardogobbosouza** [comment]
Hi @aerni 
Sorry for the late reply.

Try using the methods:
```php
\Cknow\Money\Money::setLocale(Config::get('my_package.locale'));
\Cknow\Money\Money::setCurrencies(Config::get('my_package.currency'));
```
