### ISSUE TITLE
Get amount formatted correctly, but without prefix/suffix

### ISSUE THREAD

**Issue by simplenotezy** [cknow/laravel-money#7]
I am missing a method to format a number into the local format. The closest I can get is using `format`, but it includes the currency (suffix/prefix) but I only want the amount formatted.

    money('1,5', 'DKK', true)->format() // gives me: 1,50kr. I only want: 1,50

This method could do the trick:

    /**
     * format amount.
     *
     * @return string
     */
    public function formatAmount()
    {
        $negative = $this->isNegative();
        $value = $this->getValue();
        $amount = $negative ? -$value : $value;
        $thousands = $this->currency->getThousandsSeparator();
        $decimals = $this->currency->getDecimalMark();

        return number_format($amount, 2, $decimals, $thousands);
    }

**Comment by ricardogobbosouza** [comment]
Use function `formatSimple`

```
money('1,5', 'DKK', true)->formatSimple() // 1,50
```
