### ISSUE TITLE
How to remove decimals

### ISSUE THREAD

**Issue by Echecivuole** [cknow/laravel-money#77]
Hello,

I am not able to find any option to show amounts without decimals directly using Laravel-money. I could do using php, but if I have laravel money package installed I guess there is easier way.

thanks

**Comment by ricardogobbosouza** [comment]
Hi @Echecivuole 
You can create custom formatter 
https://github.com/cknow/laravel-money#create-your-formatter

**Comment by jigapate** [comment]
@ricardogobbosouza , can formatter used to convert 5.00 output to 500?

**Comment by ricardogobbosouza** [comment]
Hi @Echecivuole 
You can use 

```php
money(500)->format(null, null, \NumberFormatter::DECIMAL)
```

See https://www.php.net/manual/pt_BR/class.numberformatter.php

**Comment by Echecivuole** [comment]
> Hi @Echecivuole You can create custom formatter https://github.com/cknow/laravel-money#create-your-formatter

thanks but not working and time consuming to manage it. Strange this library does not consider to show automatically decimals which are present or not....
