### ISSUE TITLE
Feature Request: Currency validation helper method

### ISSUE THREAD

**Issue by natepisarski** [cknow/laravel-money#81]
I think it would be helpful if this package could include something along the lines of `Money::isValidCurrency(string): bool`.

This way `Money::isValidCurrency('USD')` can be true and `Money::isValidCurrency('blarg')` can be false.

In the case where both the amount AND currency type is unknown, there is currently no way of checking that the currency is a type that this package understands. The only other way to check it would be with `is_callable(Money::class, 'currency')`, but because of the `__call` magic this always passes as being true.

Currently the only workaround is to export an array constant from the `MoneyFactory.php` file and check against it, which is obviously cumbersome because it can fall out of sync with the package if more support is added, and it adds a huge constant to dependent codebases.

**Comment by ricardogobbosouza** [comment]
Sorry for the delay, I will analyze this week
