### ISSUE TITLE
Calculation on real values instead of cents

### ISSUE THREAD

**Issue by jigapate** [cknow/laravel-money#82]
Hello,

@money(17000, 'INR')
//This returns ₹170.00

But want to return it as ₹17,000.00

Is there any way to change its internals so that it should return as required?

Why it calculate on cents?

Also, how can we only show numbers without currency symbols?

**Comment by ricardogobbosouza** [comment]
Hi @jigapate 

Cents too is money 😄 

````php
@money(1700000, 'INR')->formatByDecimal()
````

You can use `formatByDecimal` see https://github.com/cknow/laravel-money#advanced-usage
