### ISSUE TITLE
Position of symbol

### ISSUE THREAD

**Issue by lungu-catalin** [cknow/laravel-money#83]
Hi,

It's possible to put the symbol at the end of the number? Also is possible to use EUR instead € ? Something like this: 1.234,00 EUR

Thanks

**Comment by ricardogobbosouza** [comment]
Hi @lungu-catalin 
You can create your own formatter
https://github.com/cknow/laravel-money#create-your-formatter

**Comment by ricardogobbosouza** [comment]
I'm going to add a formatter for this.
Many ask for it =)

**Comment by ricardogobbosouza** [comment]
Hi @lungu-catalin
Added new formatter [`CurrencySymbolMoneyFormatter`](#94 )
