### ISSUE TITLE
Feature Request: Currency help function.

### ISSUE THREAD

**Issue by Cyrtolat** [cknow/laravel-money#95]
I noticed that the `currency()` function throws an exception in the absence of an argument, and does not return a standard currency object, as the `money()` function does. After looking at the source code, I saw that you pass the argument directly to the constructor. Meanwhile, I consider it necessary to suggest returning the standard currency object in the absence of an argument. This is often extremely necessary. For example, the code could be written like this:

`
     function currency($currency = null)
     {
          return new Money\Currency($currency ?: Cknow\Money\Money::getDefaultCurrency());
     }
`

**Comment by ricardogobbosouza** [comment]
Hi @Cyrtolat
Thanks for reporting

Makes sense ... I'll implement
